server:
  port: 8778
  servlet:
    context-path: /api  

spring:
  security:
    user:
      name: user
      password: password
      roles: USER

  datasource:
    flow-connect:
      url: jdbc:sqlserver://localhost:1401;databaseName=flow_connect;encrypt=true;trustServerCertificate=true;
      username: sa
      password: P@ssw0rd
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    communication-hub:
      url: jdbc:sqlserver://localhost:1401;databaseName=communication_hub;encrypt=true;trustServerCertificate=true;
      username: sa
      password: P@ssw0rd
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none # Set to 'none' to ensure Liquibase manages schema
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

  mail:
    default:
      host: smtp.gmail.com
      port: 587
      username: your-gmail@gmail.com
      password: your-gmail-password
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
    alternate:
      host: smtp.sendgrid.net
      port: 587
      username: your-sendgrid-user
      password: your-sendgrid-password
      properties:
        mail.smtp.auth: true
        mail.smtp.starttls.enable: true
        mail.smtp.starttls.required: true
